// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYyggoTT1QUJ8OH1KwAWGRA1mQ4C0T6dU',
    appId: '1:458346641431:web:9bb34c199f28277863c452',
    messagingSenderId: '458346641431',
    projectId: 'flutter-app-9b2eb',
    authDomain: 'flutter-app-9b2eb.firebaseapp.com',
    databaseURL: 'https://flutter-app-9b2eb-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-9b2eb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDWhST-kSCzwguIE5u1Hr36pLY8bYyvF8',
    appId: '1:458346641431:android:dc9a974fa72a12b563c452',
    messagingSenderId: '458346641431',
    projectId: 'flutter-app-9b2eb',
    databaseURL: 'https://flutter-app-9b2eb-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-9b2eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlsvABQVTuavNiP11gTqDCbwvQBaEKDqw',
    appId: '1:458346641431:ios:cd60c8bb9690888263c452',
    messagingSenderId: '458346641431',
    projectId: 'flutter-app-9b2eb',
    databaseURL: 'https://flutter-app-9b2eb-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-9b2eb.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlsvABQVTuavNiP11gTqDCbwvQBaEKDqw',
    appId: '1:458346641431:ios:cd60c8bb9690888263c452',
    messagingSenderId: '458346641431',
    projectId: 'flutter-app-9b2eb',
    databaseURL: 'https://flutter-app-9b2eb-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-9b2eb.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYyggoTT1QUJ8OH1KwAWGRA1mQ4C0T6dU',
    appId: '1:458346641431:web:05236382bf51cb3b63c452',
    messagingSenderId: '458346641431',
    projectId: 'flutter-app-9b2eb',
    authDomain: 'flutter-app-9b2eb.firebaseapp.com',
    databaseURL: 'https://flutter-app-9b2eb-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-9b2eb.firebasestorage.app',
  );
}
